### ISSUE TITLE
Create View Schedule page to show result of sleep/wake time (200pts)

### ISSUE THREAD

**Issue by sassanhashemi** [ucsb-cs56-f18/ucsb-cs56-goodsleepalarm#3]

**Comment by fzhao06** [comment]
This page will be the home page that displays sleep / wake time calculated by the backend. 
This page should update every time the algorithm for these times is run (since the times may change) such as for the next day or modified events.
May need a refresh button to update times (or page auto-updates).

**Comment by rphammy** [comment]
Mentor Approved
